apiVersion: v1
kind: ConfigMap
metadata:
  name: brats-paths
data:
  paths_config.py: |
    # Override paths to use the PVC mount
    RAW_DATASET_PATH = "/data/extracted/BraTS2020_training_data/content/data"
    PROCESSED_PATH = "/data/processed_data/brats128"
    FINAL_DATA_PATH = "/data/processed_data/brats128_split"