apiVersion: v1
kind: Pod
metadata:
  name: misc
spec:
  containers:
    - name: brats-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /app/BraTS-CycleGAN-SwinUNETR
      command:
        - "bash"
        - "-c"
      args:
        - |
          git clone https://gitlab.nrp-nautilus.io/timothy.sereda/BraTS-CycleGAN-SwinUNETR ${REPO_PATH}
          cd ${REPO_PATH}

          sleep infinity
      volumeMounts:
        - name: git-repo
          mountPath: /app
        - name: brats-data
          mountPath: /data
        - name: brats-data-mny
          mountPath: /data-mny
        - name: dshm
          mountPath: /dev/shm
      resources:
        limits:
          memory: 24Gi
          cpu: "12"
          nvidia.com/gpu: "1"
        requests:
          memory: 20Gi
          cpu: "10"
          nvidia.com/gpu: "1"
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: brats-data-mny
      persistentVolumeClaim:
        claimName: brats-data-mny
    - name: brats-data
      persistentVolumeClaim:
        claimName: brats-data
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
  restartPolicy: Never