apiVersion: v1
kind: Pod
metadata:
  name: brats-processing-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 100
    fsGroup: 100
  containers:
  - name: brats-processing
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
    env:
    - name: REPO_PATH
      value: /opt/repo/BraTS-CycleGAN-SwinUNETR
    command:
    - "bash"
    - "-c"
    args:
    - |
      # --- User and Environment Setup ---
      echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
      # --- Git Repository Update ---
      echo "Updating Git repository..."
      cd ${REPO_PATH}
      git pull origin main || { echo "Failed to update git repository"; exit 1; }
      echo "Git repository updated"
      # Preprocessing
      echo "Copying the dataset from pvc..."
      cp /data/brats-data-many/brats20-dataset-training-validation.zip .
      unzip brats20-dataset-training-validation.zip
      mkdir -p processed
      pip install nibabel
      python3 data_preprocessing.py --input_train BraTS2020_TrainingData/MICCAI_BraTS2020_TrainingData/ --input_val BraTS2020_ValidationData/MICCAI_BraTS2020_ValidationData/
      python3 validate_data.py
      # Cleanup intermediate processed directories after validation
      echo "Removing intermediate processing directories to save space..."
      rm -rf processed/brats128_training processed/brats128_validation
      echo "Keeping only final split and cyclegan datasets"
      # Install compression tools
      sudo apt-get update && sudo apt-get install -y pigz pv
      # Compress only the necessary processed data
      echo "Compressing final processed data..."
      cd ${REPO_PATH} && \
      sudo tar -cf - -C processed . | pv | sudo pigz -p $(nproc) | sudo tee /data/brats-data-many/brats128_processed_$(date +%Y%m%d_%H%M%S).tar.gz > /dev/null
      echo "Sleeping indefinitely."
      sleep infinity
    volumeMounts:
    - name: git-repo
      mountPath: /opt/repo
    - name: brats-data-volume
      mountPath: /data/brats-data
    - name: brats-data-many-volume
      mountPath: /data/brats-data-many
    - name: dshm
      mountPath: /dev/shm
    resources:
      limits:
        memory: 24Gi
        cpu: "12"
        nvidia.com/gpu: "1"
      requests:
        memory: 20Gi
        cpu: "10"
        nvidia.com/gpu: "1"
  initContainers:
  - name: init-git-repo
    image: alpine/git
    args:
    - clone
    - --single-branch
    - -b
    - main
    - https://github.com/tsereda/BraTS-CycleGAN-SwinUNETR
    - /opt/repo/BraTS-CycleGAN-SwinUNETR
    volumeMounts:
    - name: git-repo
      mountPath: /opt/repo
    - name: local-processing
      mountPath: /local-processing
    resources:
      limits:
        memory: 307Mi
        cpu: 240m
      requests:
        memory: 256Mi
        cpu: 200m
  volumes:
  - name: git-repo
    emptyDir: {}
  - name: local-processing
    emptyDir: {}
  - name: brats-data-volume
    persistentVolumeClaim:
      claimName: brats-data
  - name: brats-data-many-volume
    persistentVolumeClaim:
      claimName: brats-data-many
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 8Gi
  restartPolicy: Never