apiVersion: v1
kind: Pod
metadata:
  name: transfer-pod
spec:
  containers:
  - name: transfer-container
    image: ubuntu
    command: ["sleep", "6600"]
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: brats-data
  restartPolicy: Never